name: Docker to HuaweiCloud SWR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'images.txt'

env:
  HUAWEICLOUD_REGISTRY: "${{ secrets.HW_REGISTRY }}" 
  HUAWEICLOUD_ORG_NAME: "${{ secrets.HW_ORG_NAME }}" 
  HUAWEICLOUD_USER: "${{ secrets.HW_REGISTRY_USER }}" 
  HUAWEICLOUD_PASSWORD: "${{ secrets.HW_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Images Push to SWR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt-get update

    - name: Login, process and push images
      run: bash push_images.sh
      env:
        HUAWEICLOUD_REGISTRY: ${{ secrets.HW_REGISTRY }}
        HUAWEICLOUD_ORG_NAME: ${{ secrets.HW_ORG_NAME }}
        HUAWEICLOUD_USER: ${{ secrets.HW_REGISTRY_USER }}
        HUAWEICLOUD_PASSWORD: ${{ secrets.HW_REGISTRY_PASSWORD }}
